# Write etl/hadith_placement.sql from the combined vote (combine.py) plus manual overrides.
import csv, sys, pickle, collections
S, OUT = sys.argv[1], sys.argv[2]
final2, ev = pickle.load(open(f'{S}/final2.pkl', 'rb'))
seq = {r['seq']: int(r['bab_seq']) for r in csv.DictReader(open(f'{S}/x_babseq.csv'))}
order = list(csv.DictReader(open(f'{S}/x_order.csv')))
# Hand-checked (docs/research/lk-kitab-bab-findings.md §6).
MANUAL = {
    '17532': (34, 4, 'Muslim 1935: sea animals; a shared isnad pulled fuzzy votes to kitab 24'),
    '17666': (35, 5, 'Muslim 1977 a/b: the site files them in bab 5 of kitab 35'),
    '15695': ('15697', None, 'isnad fragment of Muslim 1365'),
    '15696': ('15697', None, 'isnad fragment of Muslim 1365'),
    '15703': ('15697', None, 'isnad fragment of Muslim 1365'),
    '19710': ('19709', None, 'isnad fragment of Muslim 157'),
}
def target(h):
    t = final2[h][0]
    return (t[0], seq[t[1]] if t[1] else None) if t else None
# Muslim's Muqaddimah (issue #18): 40 numberless records that the extractor now
# keeps (manifest unnumbered_label). Each Ifta chapter title names exactly one
# bab of the Introduction (kitab 0) on sunnah.com; the preface comes before the
# first bab. fm.csv: book, mainId, previous number, chapter, text.
MUQADDIMAH = {
    'مقدمة': (None, 'preface, before the first bab'),
    'باب وجوب الرواية عَنْ الثقات وترك الكذابين': (1, 'bab 1'),
    'باب فِي أن الإسناد من الدين': (5, 'bab 5 (site Introduction 26-32)'),
    'باب الكشف عَنْ معايب رواة الحديث ونقلة الْأخبار وقول الْأئمة': (6, 'bab 6 (5B)'),
    'باب ما تصح به رواية الرواة بعضهم عَنْ بعض والتنبيه على من غل': (7, 'bab 7 (5C)'),
    'باب صحة الاحتجاج بالحديث المعنعن': (8, 'bab 8 (6)'),
}
csv.field_size_limit(10**9)
muq = []
for r in csv.reader(open(f'{S}/fm.csv')):
    if r[0] != 'sahih-muslim': continue
    key = next(k for k in MUQADDIMAH if r[3].startswith(k))
    muq.append((int(r[1]), *MUQADDIMAH[key]))
assert len(muq) == 40, len(muq)

rows, via = [], collections.Counter()
for h, s_, note in muq:
    via['M'] += 1
    rows.append(f"({h},0,{'NULL' if s_ is None else s_},'M')  -- Muqaddimah (#18): {note}")
for r in order:
    h = r['hadith_id']
    if h in MANUAL:
        a, b, why = MANUAL[h]
        k, s = target(a) if isinstance(a, str) else (a, b)
        v, note = 'M', why
    else:
        t, e = final2[h][0], ev.get(h, {})
        k, s = target(h)
        v = ('T' if any(e.get(m) == t for m in ('sn_text', 'lk_text'))
             else 'F' if any(e.get(m) == t for m in ('sn_fuzzy', 'lk_fuzzy')) else 'S')
        note = None
    via[v] += 1
    rows.append(f"({h},{k},{'NULL' if s is None else s},'{v}')" + (f"  -- {note}" if note else ''))
with open(OUT, 'w') as f:
    f.write("""-- hadith_placement.sql — curated. Places every Ifta hadith in a sunnah.com
-- (kitab, bab). Generated by docs/research/scripts/combine.py and
-- gen_placement.py; see docs/research/lk-kitab-bab-findings.md.
--
-- Columns: hadith_id, kitab_num, bab_seq (the bab's page position inside the
-- kitab; NULL = the hadith sits at kitab level, as on the site), via:
--   T = text match (stage-14 tiers against the sunnah.com dump or LK)
--   F = fuzzy match (two strong string metrics agree)
--   S = structure only (neighbours, chapter, number, title)
--   M = manual, with the reason
--
-- Load after db/03_staging.sql and etl/sunnah_structure.sql:
--   psql -f sunnah_structure.sql -f hadith_placement.sql
TRUNCATE staging.placement;
INSERT INTO staging.placement (hadith_id, kitab_num, bab_seq, via) VALUES
""")
    for i, line in enumerate(rows):
        body, _, note = line.partition('  -- ')
        f.write(body + (',' if i < len(rows) - 1 else ';') + (f'  -- {note}' if note else '') + '\n')
print(dict(via), len(rows))
