/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedAdminVerifyRouteImport } from './routes/_authed/admin/verify'
import { Route as AuthedAnalyticsIndexRouteImport } from './routes/_authed/analytics/index'
import { Route as AuthedAnalyticsContestedRouteImport } from './routes/_authed/analytics/contested'
import { Route as AuthedAnalyticsSharedRouteImport } from './routes/_authed/analytics/shared'
import { Route as AuthedAnalyticsTopNarratorsRouteImport } from './routes/_authed/analytics/top-narrators'
import { Route as AuthedAnalyticsWeakestChainsRouteImport } from './routes/_authed/analytics/weakest-chains'
import { Route as AuthedAssignmentsAssignmentIdRouteImport } from './routes/_authed/assignments/$assignmentId'
import { Route as AuthedCirclesIndexRouteImport } from './routes/_authed/circles/index'
import { Route as AuthedCirclesCircleIdRouteRouteImport } from './routes/_authed/circles/$circleId/route'
import { Route as AuthedCollectionsIndexRouteImport } from './routes/_authed/collections/index'
import { Route as AuthedCollectionsSlugRouteImport } from './routes/_authed/collections/$slug'
import { Route as AuthedHadithsHadithIdRouteImport } from './routes/_authed/hadiths/$hadithId'
import { Route as AuthedNarratorsIndexRouteImport } from './routes/_authed/narrators/index'
import { Route as AuthedNarratorsNarratorIdRouteImport } from './routes/_authed/narrators/$narratorId'
import { Route as AuthedNotesIndexRouteImport } from './routes/_authed/notes/index'
import { Route as AuthedReviewSessionIdRouteImport } from './routes/_authed/review/$sessionId'
import { Route as AuthedSetsIndexRouteImport } from './routes/_authed/sets/index'
import { Route as AuthedSetsSetIdRouteImport } from './routes/_authed/sets/$setId'
import { Route as AuthedStudentsIndexRouteImport } from './routes/_authed/students/index'
import { Route as AuthedStudentsStudentIdRouteImport } from './routes/_authed/students/$studentId'
import { Route as AuthedCirclesCircleIdIndexRouteImport } from './routes/_authed/circles/$circleId/index'
import { Route as AuthedCirclesCircleIdAssignRouteImport } from './routes/_authed/circles/$circleId/assign'
import { Route as AuthedCollectionsSlugKitabRouteImport } from './routes/_authed/collections/$slug_.$kitab'
import { Route as AuthedCollectionsSlugKitabBabRouteImport } from './routes/_authed/collections/$slug_.$kitab_.$bab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminVerifyRoute = AuthedAdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsIndexRoute = AuthedAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsContestedRoute =
  AuthedAnalyticsContestedRouteImport.update({
    id: '/analytics/contested',
    path: '/analytics/contested',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAnalyticsSharedRoute = AuthedAnalyticsSharedRouteImport.update({
  id: '/analytics/shared',
  path: '/analytics/shared',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsTopNarratorsRoute =
  AuthedAnalyticsTopNarratorsRouteImport.update({
    id: '/analytics/top-narrators',
    path: '/analytics/top-narrators',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAnalyticsWeakestChainsRoute =
  AuthedAnalyticsWeakestChainsRouteImport.update({
    id: '/analytics/weakest-chains',
    path: '/analytics/weakest-chains',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAssignmentsAssignmentIdRoute =
  AuthedAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCirclesIndexRoute = AuthedCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCirclesCircleIdRouteRoute =
  AuthedCirclesCircleIdRouteRouteImport.update({
    id: '/circles/$circleId',
    path: '/circles/$circleId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCollectionsIndexRoute = AuthedCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsSlugRoute = AuthedCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHadithsHadithIdRoute = AuthedHadithsHadithIdRouteImport.update({
  id: '/hadiths/$hadithId',
  path: '/hadiths/$hadithId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNarratorsIndexRoute = AuthedNarratorsIndexRouteImport.update({
  id: '/narrators/',
  path: '/narrators/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNarratorsNarratorIdRoute =
  AuthedNarratorsNarratorIdRouteImport.update({
    id: '/narrators/$narratorId',
    path: '/narrators/$narratorId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNotesIndexRoute = AuthedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewSessionIdRoute = AuthedReviewSessionIdRouteImport.update({
  id: '/review/$sessionId',
  path: '/review/$sessionId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetsIndexRoute = AuthedSetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetsSetIdRoute = AuthedSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentsIndexRoute = AuthedStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentsStudentIdRoute = AuthedStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCirclesCircleIdIndexRoute =
  AuthedCirclesCircleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCirclesCircleIdRouteRoute,
  } as any)
const AuthedCirclesCircleIdAssignRoute =
  AuthedCirclesCircleIdAssignRouteImport.update({
    id: '/assign',
    path: '/assign',
    getParentRoute: () => AuthedCirclesCircleIdRouteRoute,
  } as any)
const AuthedCollectionsSlugKitabRoute =
  AuthedCollectionsSlugKitabRouteImport.update({
    id: '/collections/$slug_/$kitab',
    path: '/collections/$slug/$kitab',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCollectionsSlugKitabBabRoute =
  AuthedCollectionsSlugKitabBabRouteImport.update({
    id: '/collections/$slug_/$kitab_/$bab',
    path: '/collections/$slug/$kitab/$bab',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me': typeof AuthedMeRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/circles/$circleId': typeof AuthedCirclesCircleIdRouteRouteWithChildren
  '/admin/verify': typeof AuthedAdminVerifyRoute
  '/analytics/contested': typeof AuthedAnalyticsContestedRoute
  '/analytics/shared': typeof AuthedAnalyticsSharedRoute
  '/analytics/top-narrators': typeof AuthedAnalyticsTopNarratorsRoute
  '/analytics/weakest-chains': typeof AuthedAnalyticsWeakestChainsRoute
  '/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/narrators/$narratorId': typeof AuthedNarratorsNarratorIdRoute
  '/review/$sessionId': typeof AuthedReviewSessionIdRoute
  '/sets/$setId': typeof AuthedSetsSetIdRoute
  '/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/analytics/': typeof AuthedAnalyticsIndexRoute
  '/circles/': typeof AuthedCirclesIndexRoute
  '/collections/': typeof AuthedCollectionsIndexRoute
  '/narrators/': typeof AuthedNarratorsIndexRoute
  '/notes/': typeof AuthedNotesIndexRoute
  '/sets/': typeof AuthedSetsIndexRoute
  '/students/': typeof AuthedStudentsIndexRoute
  '/circles/$circleId/assign': typeof AuthedCirclesCircleIdAssignRoute
  '/collections/$slug/$kitab': typeof AuthedCollectionsSlugKitabRoute
  '/circles/$circleId/': typeof AuthedCirclesCircleIdIndexRoute
  '/collections/$slug/$kitab/$bab': typeof AuthedCollectionsSlugKitabBabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me': typeof AuthedMeRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/verify': typeof AuthedAdminVerifyRoute
  '/analytics/contested': typeof AuthedAnalyticsContestedRoute
  '/analytics/shared': typeof AuthedAnalyticsSharedRoute
  '/analytics/top-narrators': typeof AuthedAnalyticsTopNarratorsRoute
  '/analytics/weakest-chains': typeof AuthedAnalyticsWeakestChainsRoute
  '/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/narrators/$narratorId': typeof AuthedNarratorsNarratorIdRoute
  '/review/$sessionId': typeof AuthedReviewSessionIdRoute
  '/sets/$setId': typeof AuthedSetsSetIdRoute
  '/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/analytics': typeof AuthedAnalyticsIndexRoute
  '/circles': typeof AuthedCirclesIndexRoute
  '/collections': typeof AuthedCollectionsIndexRoute
  '/narrators': typeof AuthedNarratorsIndexRoute
  '/notes': typeof AuthedNotesIndexRoute
  '/sets': typeof AuthedSetsIndexRoute
  '/students': typeof AuthedStudentsIndexRoute
  '/circles/$circleId/assign': typeof AuthedCirclesCircleIdAssignRoute
  '/collections/$slug/$kitab': typeof AuthedCollectionsSlugKitabRoute
  '/circles/$circleId': typeof AuthedCirclesCircleIdIndexRoute
  '/collections/$slug/$kitab/$bab': typeof AuthedCollectionsSlugKitabBabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/me': typeof AuthedMeRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/circles/$circleId': typeof AuthedCirclesCircleIdRouteRouteWithChildren
  '/_authed/admin/verify': typeof AuthedAdminVerifyRoute
  '/_authed/analytics/contested': typeof AuthedAnalyticsContestedRoute
  '/_authed/analytics/shared': typeof AuthedAnalyticsSharedRoute
  '/_authed/analytics/top-narrators': typeof AuthedAnalyticsTopNarratorsRoute
  '/_authed/analytics/weakest-chains': typeof AuthedAnalyticsWeakestChainsRoute
  '/_authed/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/_authed/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/_authed/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/_authed/narrators/$narratorId': typeof AuthedNarratorsNarratorIdRoute
  '/_authed/review/$sessionId': typeof AuthedReviewSessionIdRoute
  '/_authed/sets/$setId': typeof AuthedSetsSetIdRoute
  '/_authed/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/_authed/analytics/': typeof AuthedAnalyticsIndexRoute
  '/_authed/circles/': typeof AuthedCirclesIndexRoute
  '/_authed/collections/': typeof AuthedCollectionsIndexRoute
  '/_authed/narrators/': typeof AuthedNarratorsIndexRoute
  '/_authed/notes/': typeof AuthedNotesIndexRoute
  '/_authed/sets/': typeof AuthedSetsIndexRoute
  '/_authed/students/': typeof AuthedStudentsIndexRoute
  '/_authed/circles/$circleId/assign': typeof AuthedCirclesCircleIdAssignRoute
  '/_authed/collections/$slug_/$kitab': typeof AuthedCollectionsSlugKitabRoute
  '/_authed/circles/$circleId/': typeof AuthedCirclesCircleIdIndexRoute
  '/_authed/collections/$slug_/$kitab_/$bab': typeof AuthedCollectionsSlugKitabBabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/me'
    | '/search'
    | '/settings'
    | '/circles/$circleId'
    | '/admin/verify'
    | '/analytics/contested'
    | '/analytics/shared'
    | '/analytics/top-narrators'
    | '/analytics/weakest-chains'
    | '/assignments/$assignmentId'
    | '/collections/$slug'
    | '/hadiths/$hadithId'
    | '/narrators/$narratorId'
    | '/review/$sessionId'
    | '/sets/$setId'
    | '/students/$studentId'
    | '/analytics/'
    | '/circles/'
    | '/collections/'
    | '/narrators/'
    | '/notes/'
    | '/sets/'
    | '/students/'
    | '/circles/$circleId/assign'
    | '/collections/$slug/$kitab'
    | '/circles/$circleId/'
    | '/collections/$slug/$kitab/$bab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/me'
    | '/search'
    | '/settings'
    | '/admin/verify'
    | '/analytics/contested'
    | '/analytics/shared'
    | '/analytics/top-narrators'
    | '/analytics/weakest-chains'
    | '/assignments/$assignmentId'
    | '/collections/$slug'
    | '/hadiths/$hadithId'
    | '/narrators/$narratorId'
    | '/review/$sessionId'
    | '/sets/$setId'
    | '/students/$studentId'
    | '/analytics'
    | '/circles'
    | '/collections'
    | '/narrators'
    | '/notes'
    | '/sets'
    | '/students'
    | '/circles/$circleId/assign'
    | '/collections/$slug/$kitab'
    | '/circles/$circleId'
    | '/collections/$slug/$kitab/$bab'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/me'
    | '/_authed/search'
    | '/_authed/settings'
    | '/_authed/circles/$circleId'
    | '/_authed/admin/verify'
    | '/_authed/analytics/contested'
    | '/_authed/analytics/shared'
    | '/_authed/analytics/top-narrators'
    | '/_authed/analytics/weakest-chains'
    | '/_authed/assignments/$assignmentId'
    | '/_authed/collections/$slug'
    | '/_authed/hadiths/$hadithId'
    | '/_authed/narrators/$narratorId'
    | '/_authed/review/$sessionId'
    | '/_authed/sets/$setId'
    | '/_authed/students/$studentId'
    | '/_authed/analytics/'
    | '/_authed/circles/'
    | '/_authed/collections/'
    | '/_authed/narrators/'
    | '/_authed/notes/'
    | '/_authed/sets/'
    | '/_authed/students/'
    | '/_authed/circles/$circleId/assign'
    | '/_authed/collections/$slug_/$kitab'
    | '/_authed/circles/$circleId/'
    | '/_authed/collections/$slug_/$kitab_/$bab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/verify': {
      id: '/_authed/admin/verify'
      path: '/admin/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AuthedAdminVerifyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics/': {
      id: '/_authed/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthedAnalyticsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics/contested': {
      id: '/_authed/analytics/contested'
      path: '/analytics/contested'
      fullPath: '/analytics/contested'
      preLoaderRoute: typeof AuthedAnalyticsContestedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics/shared': {
      id: '/_authed/analytics/shared'
      path: '/analytics/shared'
      fullPath: '/analytics/shared'
      preLoaderRoute: typeof AuthedAnalyticsSharedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics/top-narrators': {
      id: '/_authed/analytics/top-narrators'
      path: '/analytics/top-narrators'
      fullPath: '/analytics/top-narrators'
      preLoaderRoute: typeof AuthedAnalyticsTopNarratorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics/weakest-chains': {
      id: '/_authed/analytics/weakest-chains'
      path: '/analytics/weakest-chains'
      fullPath: '/analytics/weakest-chains'
      preLoaderRoute: typeof AuthedAnalyticsWeakestChainsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assignments/$assignmentId': {
      id: '/_authed/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/circles/': {
      id: '/_authed/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AuthedCirclesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/circles/$circleId': {
      id: '/_authed/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof AuthedCirclesCircleIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/': {
      id: '/_authed/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthedCollectionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$slug': {
      id: '/_authed/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof AuthedCollectionsSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hadiths/$hadithId': {
      id: '/_authed/hadiths/$hadithId'
      path: '/hadiths/$hadithId'
      fullPath: '/hadiths/$hadithId'
      preLoaderRoute: typeof AuthedHadithsHadithIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/narrators/': {
      id: '/_authed/narrators/'
      path: '/narrators'
      fullPath: '/narrators/'
      preLoaderRoute: typeof AuthedNarratorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/narrators/$narratorId': {
      id: '/_authed/narrators/$narratorId'
      path: '/narrators/$narratorId'
      fullPath: '/narrators/$narratorId'
      preLoaderRoute: typeof AuthedNarratorsNarratorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes/': {
      id: '/_authed/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthedNotesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/review/$sessionId': {
      id: '/_authed/review/$sessionId'
      path: '/review/$sessionId'
      fullPath: '/review/$sessionId'
      preLoaderRoute: typeof AuthedReviewSessionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sets/': {
      id: '/_authed/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof AuthedSetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sets/$setId': {
      id: '/_authed/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof AuthedSetsSetIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/students/': {
      id: '/_authed/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthedStudentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/students/$studentId': {
      id: '/_authed/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthedStudentsStudentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/circles/$circleId/': {
      id: '/_authed/circles/$circleId/'
      path: '/'
      fullPath: '/circles/$circleId/'
      preLoaderRoute: typeof AuthedCirclesCircleIdIndexRouteImport
      parentRoute: typeof AuthedCirclesCircleIdRouteRoute
    }
    '/_authed/circles/$circleId/assign': {
      id: '/_authed/circles/$circleId/assign'
      path: '/assign'
      fullPath: '/circles/$circleId/assign'
      preLoaderRoute: typeof AuthedCirclesCircleIdAssignRouteImport
      parentRoute: typeof AuthedCirclesCircleIdRouteRoute
    }
    '/_authed/collections/$slug_/$kitab': {
      id: '/_authed/collections/$slug_/$kitab'
      path: '/collections/$slug/$kitab'
      fullPath: '/collections/$slug/$kitab'
      preLoaderRoute: typeof AuthedCollectionsSlugKitabRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$slug_/$kitab_/$bab': {
      id: '/_authed/collections/$slug_/$kitab_/$bab'
      path: '/collections/$slug/$kitab/$bab'
      fullPath: '/collections/$slug/$kitab/$bab'
      preLoaderRoute: typeof AuthedCollectionsSlugKitabBabRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedCirclesCircleIdRouteRouteChildren {
  AuthedCirclesCircleIdAssignRoute: typeof AuthedCirclesCircleIdAssignRoute
  AuthedCirclesCircleIdIndexRoute: typeof AuthedCirclesCircleIdIndexRoute
}

const AuthedCirclesCircleIdRouteRouteChildren: AuthedCirclesCircleIdRouteRouteChildren =
  {
    AuthedCirclesCircleIdAssignRoute: AuthedCirclesCircleIdAssignRoute,
    AuthedCirclesCircleIdIndexRoute: AuthedCirclesCircleIdIndexRoute,
  }

const AuthedCirclesCircleIdRouteRouteWithChildren =
  AuthedCirclesCircleIdRouteRoute._addFileChildren(
    AuthedCirclesCircleIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedCirclesCircleIdRouteRoute: typeof AuthedCirclesCircleIdRouteRouteWithChildren
  AuthedAdminVerifyRoute: typeof AuthedAdminVerifyRoute
  AuthedAnalyticsContestedRoute: typeof AuthedAnalyticsContestedRoute
  AuthedAnalyticsSharedRoute: typeof AuthedAnalyticsSharedRoute
  AuthedAnalyticsTopNarratorsRoute: typeof AuthedAnalyticsTopNarratorsRoute
  AuthedAnalyticsWeakestChainsRoute: typeof AuthedAnalyticsWeakestChainsRoute
  AuthedAssignmentsAssignmentIdRoute: typeof AuthedAssignmentsAssignmentIdRoute
  AuthedCollectionsSlugRoute: typeof AuthedCollectionsSlugRoute
  AuthedHadithsHadithIdRoute: typeof AuthedHadithsHadithIdRoute
  AuthedNarratorsNarratorIdRoute: typeof AuthedNarratorsNarratorIdRoute
  AuthedReviewSessionIdRoute: typeof AuthedReviewSessionIdRoute
  AuthedSetsSetIdRoute: typeof AuthedSetsSetIdRoute
  AuthedStudentsStudentIdRoute: typeof AuthedStudentsStudentIdRoute
  AuthedAnalyticsIndexRoute: typeof AuthedAnalyticsIndexRoute
  AuthedCirclesIndexRoute: typeof AuthedCirclesIndexRoute
  AuthedCollectionsIndexRoute: typeof AuthedCollectionsIndexRoute
  AuthedNarratorsIndexRoute: typeof AuthedNarratorsIndexRoute
  AuthedNotesIndexRoute: typeof AuthedNotesIndexRoute
  AuthedSetsIndexRoute: typeof AuthedSetsIndexRoute
  AuthedStudentsIndexRoute: typeof AuthedStudentsIndexRoute
  AuthedCollectionsSlugKitabRoute: typeof AuthedCollectionsSlugKitabRoute
  AuthedCollectionsSlugKitabBabRoute: typeof AuthedCollectionsSlugKitabBabRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMeRoute: AuthedMeRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedCirclesCircleIdRouteRoute: AuthedCirclesCircleIdRouteRouteWithChildren,
  AuthedAdminVerifyRoute: AuthedAdminVerifyRoute,
  AuthedAnalyticsContestedRoute: AuthedAnalyticsContestedRoute,
  AuthedAnalyticsSharedRoute: AuthedAnalyticsSharedRoute,
  AuthedAnalyticsTopNarratorsRoute: AuthedAnalyticsTopNarratorsRoute,
  AuthedAnalyticsWeakestChainsRoute: AuthedAnalyticsWeakestChainsRoute,
  AuthedAssignmentsAssignmentIdRoute: AuthedAssignmentsAssignmentIdRoute,
  AuthedCollectionsSlugRoute: AuthedCollectionsSlugRoute,
  AuthedHadithsHadithIdRoute: AuthedHadithsHadithIdRoute,
  AuthedNarratorsNarratorIdRoute: AuthedNarratorsNarratorIdRoute,
  AuthedReviewSessionIdRoute: AuthedReviewSessionIdRoute,
  AuthedSetsSetIdRoute: AuthedSetsSetIdRoute,
  AuthedStudentsStudentIdRoute: AuthedStudentsStudentIdRoute,
  AuthedAnalyticsIndexRoute: AuthedAnalyticsIndexRoute,
  AuthedCirclesIndexRoute: AuthedCirclesIndexRoute,
  AuthedCollectionsIndexRoute: AuthedCollectionsIndexRoute,
  AuthedNarratorsIndexRoute: AuthedNarratorsIndexRoute,
  AuthedNotesIndexRoute: AuthedNotesIndexRoute,
  AuthedSetsIndexRoute: AuthedSetsIndexRoute,
  AuthedStudentsIndexRoute: AuthedStudentsIndexRoute,
  AuthedCollectionsSlugKitabRoute: AuthedCollectionsSlugKitabRoute,
  AuthedCollectionsSlugKitabBabRoute: AuthedCollectionsSlugKitabBabRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
