/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminVerifyRouteImport } from './routes/_authed/admin/verify'
import { Route as AuthedCirclesIndexRouteImport } from './routes/_authed/circles/index'
import { Route as AuthedCollectionsIndexRouteImport } from './routes/_authed/collections/index'
import { Route as AuthedCollectionsSlugRouteImport } from './routes/_authed/collections/$slug'
import { Route as AuthedHadithsHadithIdRouteImport } from './routes/_authed/hadiths/$hadithId'
import { Route as AuthedNotesIndexRouteImport } from './routes/_authed/notes/index'
import { Route as AuthedStudentsIndexRouteImport } from './routes/_authed/students/index'
import { Route as AuthedCollectionsSlugSeqRouteImport } from './routes/_authed/collections/$slug_.$seq'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminVerifyRoute = AuthedAdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCirclesIndexRoute = AuthedCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsIndexRoute = AuthedCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsSlugRoute = AuthedCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHadithsHadithIdRoute = AuthedHadithsHadithIdRouteImport.update({
  id: '/hadiths/$hadithId',
  path: '/hadiths/$hadithId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesIndexRoute = AuthedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentsIndexRoute = AuthedStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionsSlugSeqRoute =
  AuthedCollectionsSlugSeqRouteImport.update({
    id: '/collections/$slug_/$seq',
    path: '/collections/$slug/$seq',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/verify': typeof AuthedAdminVerifyRoute
  '/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/circles/': typeof AuthedCirclesIndexRoute
  '/collections/': typeof AuthedCollectionsIndexRoute
  '/notes/': typeof AuthedNotesIndexRoute
  '/students/': typeof AuthedStudentsIndexRoute
  '/collections/$slug/$seq': typeof AuthedCollectionsSlugSeqRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthedIndexRoute
  '/admin/verify': typeof AuthedAdminVerifyRoute
  '/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/circles': typeof AuthedCirclesIndexRoute
  '/collections': typeof AuthedCollectionsIndexRoute
  '/notes': typeof AuthedNotesIndexRoute
  '/students': typeof AuthedStudentsIndexRoute
  '/collections/$slug/$seq': typeof AuthedCollectionsSlugSeqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/verify': typeof AuthedAdminVerifyRoute
  '/_authed/collections/$slug': typeof AuthedCollectionsSlugRoute
  '/_authed/hadiths/$hadithId': typeof AuthedHadithsHadithIdRoute
  '/_authed/circles/': typeof AuthedCirclesIndexRoute
  '/_authed/collections/': typeof AuthedCollectionsIndexRoute
  '/_authed/notes/': typeof AuthedNotesIndexRoute
  '/_authed/students/': typeof AuthedStudentsIndexRoute
  '/_authed/collections/$slug_/$seq': typeof AuthedCollectionsSlugSeqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/verify'
    | '/collections/$slug'
    | '/hadiths/$hadithId'
    | '/circles/'
    | '/collections/'
    | '/notes/'
    | '/students/'
    | '/collections/$slug/$seq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/admin/verify'
    | '/collections/$slug'
    | '/hadiths/$hadithId'
    | '/circles'
    | '/collections'
    | '/notes'
    | '/students'
    | '/collections/$slug/$seq'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/'
    | '/_authed/admin/verify'
    | '/_authed/collections/$slug'
    | '/_authed/hadiths/$hadithId'
    | '/_authed/circles/'
    | '/_authed/collections/'
    | '/_authed/notes/'
    | '/_authed/students/'
    | '/_authed/collections/$slug_/$seq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/verify': {
      id: '/_authed/admin/verify'
      path: '/admin/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AuthedAdminVerifyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/circles/': {
      id: '/_authed/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AuthedCirclesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/': {
      id: '/_authed/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthedCollectionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$slug': {
      id: '/_authed/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof AuthedCollectionsSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hadiths/$hadithId': {
      id: '/_authed/hadiths/$hadithId'
      path: '/hadiths/$hadithId'
      fullPath: '/hadiths/$hadithId'
      preLoaderRoute: typeof AuthedHadithsHadithIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes/': {
      id: '/_authed/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthedNotesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/students/': {
      id: '/_authed/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthedStudentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$slug_/$seq': {
      id: '/_authed/collections/$slug_/$seq'
      path: '/collections/$slug/$seq'
      fullPath: '/collections/$slug/$seq'
      preLoaderRoute: typeof AuthedCollectionsSlugSeqRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminVerifyRoute: typeof AuthedAdminVerifyRoute
  AuthedCollectionsSlugRoute: typeof AuthedCollectionsSlugRoute
  AuthedHadithsHadithIdRoute: typeof AuthedHadithsHadithIdRoute
  AuthedCirclesIndexRoute: typeof AuthedCirclesIndexRoute
  AuthedCollectionsIndexRoute: typeof AuthedCollectionsIndexRoute
  AuthedNotesIndexRoute: typeof AuthedNotesIndexRoute
  AuthedStudentsIndexRoute: typeof AuthedStudentsIndexRoute
  AuthedCollectionsSlugSeqRoute: typeof AuthedCollectionsSlugSeqRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminVerifyRoute: AuthedAdminVerifyRoute,
  AuthedCollectionsSlugRoute: AuthedCollectionsSlugRoute,
  AuthedHadithsHadithIdRoute: AuthedHadithsHadithIdRoute,
  AuthedCirclesIndexRoute: AuthedCirclesIndexRoute,
  AuthedCollectionsIndexRoute: AuthedCollectionsIndexRoute,
  AuthedNotesIndexRoute: AuthedNotesIndexRoute,
  AuthedStudentsIndexRoute: AuthedStudentsIndexRoute,
  AuthedCollectionsSlugSeqRoute: AuthedCollectionsSlugSeqRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
